# Define Docker Compose version.
version: "3"

# Define all the containers.
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=hellogov
    volumes:
      - ./data/db:/data/db

  # Webapp-dev Container.
  app-dev:
    depends_on:
      - mongo
    build: ./
    volumes:
      - ./:/usr/src/app
    ports:
     - 8080:8080
    environment:
      NODE_ENV: development
    command: /usr/src/app/entrypoint.sh
